//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_correlativos
    {
        public string empcod { get; set; }
        public string clitipo { get; set; }
        public decimal clanio { get; set; }
        public decimal clmes { get; set; }
        public Nullable<decimal> clcorrelativo { get; set; }
        public string clest { get; set; }
    
        public virtual cl_estado cl_estado { get; set; }
    }
}
