//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_enfermedades
    {
        public string empcod { get; set; }
        public string enfcod { get; set; }
        public string enfdescripcion { get; set; }
        public string enfest { get; set; }
        public Nullable<System.DateTime> enffchalt { get; set; }
        public string enfusualt { get; set; }
    }
}
