//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_gestioncl_gestiondescrip
    {
        public string empcod { get; set; }
        public string gescod { get; set; }
        public string clicod { get; set; }
        public string precod { get; set; }
        public string enfcod { get; set; }
        public string preres { get; set; }
        public string enfres { get; set; }
        public string preobs { get; set; }
    
        public virtual cl_gestioncl_gestiondescrip cl_gestioncl_gestiondescrip1 { get; set; }
        public virtual cl_gestioncl_gestiondescrip cl_gestioncl_gestiondescrip2 { get; set; }
    }
}
