//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_geo_municipios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cl_geo_municipios()
        {
            this.cl_cliente = new HashSet<cl_cliente>();
        }
    
        public string depcod { get; set; }
        public string muncod { get; set; }
        public string mundescripcion { get; set; }
        public string munest { get; set; }
        public string munusualt { get; set; }
    
        public virtual cl_geo_departamentos cl_geo_departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cl_cliente> cl_cliente { get; set; }
    }
}
