//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_gestion_cab
    {
        public string empcod { get; set; }
        public string gescod { get; set; }
        public string clicod { get; set; }
        public string gesest { get; set; }
        public Nullable<System.DateTime> gesfchalt { get; set; }
        public string gesusualt { get; set; }
    
        public virtual cl_gestion_cab cl_gestion_cab1 { get; set; }
        public virtual cl_gestion_cab cl_gestion_cab2 { get; set; }
    }
}
