//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_geo_departamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cl_geo_departamentos()
        {
            this.cl_geo_municipios = new HashSet<cl_geo_municipios>();
            this.cl_cliente = new HashSet<cl_cliente>();
        }
    
        public string depcod { get; set; }
        public string depnom { get; set; }
        public string depest { get; set; }
        public string depusualt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cl_geo_municipios> cl_geo_municipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cl_cliente> cl_cliente { get; set; }
    }
}
