//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_preguntas
    {
        public string empcod { get; set; }
        public string precod { get; set; }
        public string predescripcion { get; set; }
        public string preest { get; set; }
        public Nullable<System.DateTime> prefchalt { get; set; }
        public string preusualt { get; set; }
    
        public virtual cl_preguntas cl_preguntas1 { get; set; }
        public virtual cl_preguntas cl_preguntas2 { get; set; }
    }
}
