//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fresh0._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbfreshEntities : DbContext
    {
        public dbfreshEntities()
            : base("name=dbfreshEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cl_enfermedades> cl_enfermedades { get; set; }
        public virtual DbSet<cl_geo_departamentos> cl_geo_departamentos { get; set; }
        public virtual DbSet<cl_geo_municipios> cl_geo_municipios { get; set; }
        public virtual DbSet<cl_gestion_cab> cl_gestion_cab { get; set; }
        public virtual DbSet<cl_gestioncl_gestiondescrip> cl_gestioncl_gestiondescrip { get; set; }
        public virtual DbSet<cl_preguntas> cl_preguntas { get; set; }
        public virtual DbSet<cl_correlativos> cl_correlativos { get; set; }
        public virtual DbSet<cl_empresa> cl_empresa { get; set; }
        public virtual DbSet<cl_estado> cl_estado { get; set; }
        public virtual DbSet<cl_cliente> cl_cliente { get; set; }
    }
}
